from ._search_fields import SearchFieldsMapper
from ._issue_type import IssueTypeMapper
from ._project_category import ProjectCategoryMapper
from ._project import ProjectMapper
from ._watches import WatchesMapper
from ._priority import PriorityMapper
from ._version import VersionMapper
from ._user import UserMapper
from ._status import StatusMapper
from ._component import ComponentMapper
from ._votes import VotesMapper
from ._fields import FieldsMapper
from ._item import ItemMapper
from ._history import HistoryMapper
from ._changelog import ChangelogMapper
from ._data import DataMapper
from ._bug import BugMapper
